In [3]:
 a = 5

In [4]:
print (a)

5


In [5]:
b=3

In [6]:
print (a+b)


8


In [7]:
type (a)

int

In [8]:
def my_fun():
    print("Hello")
my_fun()

Hello


In [9]:
def add(a,b):
    print(a+b)

In [10]:
add(1,7)

8


In [11]:
def add(a,b):
    c=a+b
    print(c)

In [12]:
add(3,3)

6


In [13]:
a=[1,2,3,4,5,6,7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
text="my name is zalzameen"

In [15]:
text.split()

['my', 'name', 'is', 'zalzameen']

In [16]:
tet="my na,me is za,lzame,en"

In [17]:
tet.split(",")

['my na', 'me is za', 'lzame', 'en']

In [18]:
za=text.split()

In [19]:
za[0]

'my'

In [20]:
za[1]

'name'

In [21]:
za[-1]

'zalzameen'

In [22]:
za[2]

'is'

In [23]:
za[3]

'zalzameen'

In [24]:
f=[1,2,3,6,4,5]

for i in f:
    print(i)

1
2
3
6
4
5


In [25]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [27]:
list1=[]
t=int(input("Enter the size of array"))
for i in range(0,t):
    i=input("enter the value:")
    list1.append(i)


Enter the size of array


ValueError: invalid literal for int() with base 10: ''

In [ ]:
list1

In [32]:
import numpy as np

In [33]:
aa=np.array([1,2,3])
aa

array([1, 2, 3])

In [34]:
z=np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
r=np.arange(0,10,2)
r

array([0, 2, 4, 6, 8])

In [36]:
aa

array([1, 2, 3])

In [37]:
bb=np.array([4,5,6])
bb

array([4, 5, 6])

In [39]:
aa+bb

array([5, 7, 9])

In [40]:
np.mean(a)

5.0

In [41]:
np.max(a)

9

In [43]:
c=np.array([
    [1,2],
    [3,4]])

In [44]:
c

array([[1, 2],
       [3, 4]])

In [45]:
d=np.array([
    [4,8],
    [6,9]])


In [46]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [48]:
e=c*d

In [49]:
e

array([[ 4, 16],
       [18, 36]])

In [50]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [52]:
c.T

array([[1, 3],
       [2, 4]])

In [53]:
c

array([[1, 2],
       [3, 4]])

In [54]:
d

array([[4, 8],
       [6, 9]])

In [55]:
f

array([[16, 26],
       [36, 60]])

In [56]:
f.T

array([[16, 36],
       [26, 60]])

In [ ]:
print("\n matrix 1:\n",c)
print("\n matrix 2:\n",d)
print("\n Addition:\n",c+d)
print("\n substraction:\n",c-d)
print("\n multiplication ():\n",c)
print("\n matrix 1:\n",c)
print("\n matrix 1:\n",c)